---
author: "Daniela Palleschi"
date: "`r Sys.Date()`"
abstract: >
    Various types of world knowledge have been shown to be rapidly available during language processing, from well-known historical events to the colour of our local trains. Prior knowledge about well-known fictional or real-world referents, such as specific semantic knowledge of known cartoon or real-world referents, has also been shown to available during comprehension with gradient inter-individual effects correlated with fictional-world expertise. In an eye-tracking-during-reading experiment, we examined how rapidly two types of photo-sentence relations impact sentence comprehension. A first relation was between a photo of a cultural figure and a year in the ensuing sentence (the cultural figure in the photo was either alive in that year or not). This was contrasted with relations between the same photo and achievements or facts about the cultural figure (e.g., a film they had vs. had not starred in). Longer reading times were observed at the regions containing mismatching *year* or *fact* information (e.g., Emma Watson starred in the ***Wizard of Oz*** in ***1939***), with more robust effects when data were filtered to include only trials in which participants had accurate prior knowledge about the cultural figure, their accomplishments, and their lifetime. Effects of *fact congruence* were also found near sentence-end at the presentation of the cultural figure's name, but only when trials with missing relevant long-term knowledge were included in analyses, suggesting that this effect was driven by trials in which participants did not recognise the cultural figure. These findings indicate that long-term knowledge activated by a picture is rapidly available during the processing of information such as whether they appeared in a certain film and whether they were alive in a given year, and that the former, but not the latter, are available when prior knowledge about the cultural figure was more variable.
---

*The following text (as well as the abstract) is taken from @palleschi_activation_2022 Intro and Discussion sections, and some from DP's dissertation*

# Introduction

## Previous literature

Investigations into the role of high-level world knowledge in language processing have established that violations of long-term knowledge elicit processing costs. In their seminal study, @Hagoort2004 presented neurophsyiological evidence of the influence of specific knowledge of the world on language processing, in which violations of world knowledge elicited an N400 effect which was similar in latency and distribution to semantic violations, but with a reduced amplitude (e.g., *Dutch trains are* ***yellow/white/sour***; Dutch trains are in fact yellow). Since this study, similar findings have been found for other types of lexico-semantic world knowledge violations of well-known historical events [@Nieuwland2012; @Rapp2008], traits of familiar cartoon characters [@Filik2008; @Filik2013], even knowledge specific to the Wizarding World of Harry Potter [@Troyer2018]. 

@Troyer2018 compared semantic violations of a fictional world (the Wizarding World of Harry Potter) with those of the real-world, reporting similar N400 effects in both types of prior knowledge. Furthermore, N400 effects were graded by participant's Harry Potter expertise, with Harry Potter violations eliciting larger N400 effects in participants highly familiar with the Wizarding World of Harry Potter. Participants who scored very low in their Harry Potter familiarity showed no N400 effects in the Harry Potter violations, with no differences between participants in real-world semantic violations as a function of their Harry Potter familiarity. This effect was replicated and extended to event-related words in @Troyer2020 [see also @Troyer2020a; @Troyer2022]. Similar to @Metusalem2012, @Troyer2020 manipulated whether incongruent words were event-related (*broomstick*) or event-unrelated (*dog*) to the congruent word (*remembrall*; @exm-troyer]{ex. \ref{troyer}}). Again, individual differences in N400 effects emerged as a function of Harry Potter familiarity for the Harry Potter-related sentences and not for real-world sentences. This indicates that domain-specific familiarity relevant to the incoming linguistic signal is utilised during comprehension. In other words, the presence of relevant prior knowledge influences the processing of linguistic input, and that unexpected words that are related (*broomstick*) to the event elicit smaller processing costs than unexpected words that are unrelated to the event (*dog*). 

::: {#exm-troyer .custom}
Professor McGonagall recruits Harry for the Gryffindor Quidditch team. She saw him save Neville's *remembrall*~correct~/*broomstick*~event-related~/*dog*~event-unrelated~.
:::

It seems then that prior knowledge of both the real-world and fictional worlds, as well as historical and fictional events, is rapidly available during processing of lexico-semantic input, and that linguistic contexts can interact with this prior knowledge. However, how we define *knowledge* of real-world events is not trivial, as there is likely both inter- and intra-individual variation when it comes to common knowledge. Though most individuals would say they *know* the Earth is round and that Elvis Presley is dead, there are some who would say they *know*, or perhaps *believe*, the Earth is flat and that Elvis Presley is alive. To explore trial-level effects of prior-Harry Potter knowledge, @Troyer2020a presented 'correct' sentences (i.e., there were no violation conditions) and collected post-trial participant responses indicating familiarity with the information presented (yes or no). When trials were grouped by response, '*no*' trials (i.e., trials that presented information the participant did not already know) elicited increased N400 amplitudes compared to '*yes*' trials (i.e., trials that presented information the participant already knew). Futhermore, N400 effects in '*no*' trials were marginally stronger in participants with a low Harry Potter-familiarity score than those with a high score. The authors took this as evidence that "greater knowledge eases otherwise difficult retrieval processes" [@Troyer2020, p. 476].

Likewise, @Martin2014 presented participants with sentences describing real-world facts (e.g., @exm-martin2014), with world knowledge violations (*lawyers*) or semantic violations *horses*. Similar to @Troyer2020a, truth ratings of the items were collected in a surprise post-experimental task where participants indicated whether they believed each sentence was (a) true, (b) false, (c) that they didn't know, or (d) that they couldn't tell because the sentence was nonsensical, with an overall accuracy of 85.6\%. The authors used this information to compare P2 and N400 time-windows between trials containing semantic violations, trials that received a '*don't know*' response, and trials that presented correct sentences and received a 'true' response. 

::: {#exm-martin2014 .custom}
The Beatles were *[popstars]{.underline}/[lawyers]{.underline}/[horses]{.underline}* in the 60's.
:::

In the P2 window, '*don't know*' trials patterned with semantic violations, eliciting an increased positivity compared to '*true*' condition. In the N400 time-window, '*don't know*' trials did not differ from the '*true*' condition nor the semantic violation condition. Therefore, the P2 was sensitive to semantic violations and the inability to check plausibility when participants did not know, but the N400 was sensitive to semantic and world-knowledge violations, but not the inability to check plausibility. Importantly, these results show processing differences between trials where participants '*don't know*' if a sentence is true or even plausible and trials where sentences are known to be true, as indicated by differences in the P2 time-window.

However, our individual knowledge does not only vary in terms of factual knowledge of the world that is commonly shared in a community or culture. We each have our own individual ethical beliefs (@exm-vanBerkum2009) and personal semantics (knowledge about one's own personal preferences, @exm-Coronel2016). Each of these can modulate expectations during comprehension in a similar manner to long-term world knowledge, eliciting N400 effects. In @vanBerkum2009 participants were presented statements that were either congruent or incongruent with their personal moral beliefs about divisive topics (@exm-vanBerkum2009). Likewise, @Coronel2016 presented participants with sentences that either matched or mismatched statements describing their own personal preferences (@exm-Coronel2016). In both experiments, increased N400 amplitudes were elicited by critical words that violated the participant's personal beliefs [@vanBerkum2009] or personal semantics [@Coronel2016].

::: {#exm-vanBerkum2009 .custom}
I think the increasing emancipation of women is a negative/positive development.
:::
::: {#exm-Coronel2016 .custom}
A genre of film you like watching is horror/fantasy.
:::

Prior (world) knowledge seems then to guide expectations and to be rapidly available during comprehension, with inter- and intra-individual knowledge playing a role in a case-by-case basis. A variety of sources of information, from narrative contexts [e.g., @Nieuwland2006] to long-term knowledge of fictional worlds [@Troyer2018; @Troyer2020; @Troyer2020a; @Filik2013] or the real-world [@Hagoort2004; @Hald2007; @Metzner2015; @Martin2014], have been shown to be rapidly available during comprehension. Violations of this knowledge elicits early effects in EEG (N400 component) and eye-tracking during reading (first-fixation, first-pass reading time). Unsurprisingly, processing costs are positively correlated with our domain-specific knowledge [@Troyer2018] and the presence of sentence-specific knowledge [@Troyer2020a; @Martin2014]. Contradictions of our own personal morals and preferences elicit similar effects [@Coronel2016; @vanBerkum2009], suggesting that it is not only our shared knowledge of the world that influences language processing, but what the comprehender holds to be true. However, all these studies manipulated whether a lexical item was supported or not. The next section gives an overview of investigations into how general world knowledge and morphosyntactic information can guide anticipation during comprehension.

  These studies have demonstrated that high-level world knowledge can influence the processing of lexico-semantic input when world knowledge is activated through linguistic contexts.  Meanwhile, faces of familiar individuals can activate long-term semantic knowledge about the individual, whether they be real-world cultural figures [@AbdelRahman2002; @Suess2013] or well-known cartoon characters [@AbdelRahman2004]. Characteristics of unknown speakers have also been shown to be taken into consideration during comprehension. For example, in @vanBerkum2008 an N400 effect was elicited when participants heard statements that violated stereotypes of the speaker based on their voice (e.g., an adult male vs. female voice: *If only I looked like* ***Britney Spears*** *in her latest video*). Meanwhile, inferences about speaker nativeness, based on phsyical features of unknown faces and accompanying native or non-native accented speech, can additionally influence on-line processing of linguistic input, as well as well-formedness judgements [@Xu2019]. The rapid effects elicited by physical referent or speaker attributes indicate that what we believe to be true about an individual is rapidly available during language comprehension, whether these beliefs are based on long-term information of a known individual, or stereotypes based on demographic assumptions, like gender. Though a variety of types and sources of long-term knowledge have been investigated, such investigations have thus far focused on lexico-semantic violations activated by linguistic contexts establishing expectations based on real-world knowledge. Less is known about how long-term knowledge influences the processing of morphosyntactic relations, and how this long-term knowledge may be activated by non-linguistic contexts, such as pictures of cultural figures.

## Our findings so far

  In two eye-tracking during reading experiments we examined whether high-level information about well-known cultural figures, such as politicians and actors, is activated via a picture and available during subsequent language processing. Namely, we explored to what extent knowledge of a cultural figure's lifetime influences the processing of a given year, and whether high-level knowledge of their professional accomplishments is activated by a picture and available during sentence processing. We explored to what extent these two types of information, temporal ('year') and referential ('fact'), are activated by a photograph of a given person and subsequently available during processing. Sentences presented information that either matched or mismatched the lifetime of the cultural figure via a year, and matched or mismatched their professional accomplishments, such as appearing in a certain film. One might assume that a speaker’s face could be a strong cue to factual information associated with that speaker (e.g., what films an actress has starred in and whether she has won awards or not). Further, given the subtlety of tense effects observed in eye-tracking experiments [e.g., @Knoeferle2005, Exp 1; @Altmann2007; @Altmann2009], it may be that associations between seeing a speaker and facts about that speaker would be more influential in comprehension than associations that implicate time and perhaps lifetime status, following previous findings of processing preferences in clipart scenes [@Knoeferle2007]. Alternatively, factual knowledge (e.g., the books an author wrote, the films an actor starred in) is more probabilistic in its association with language than the arguably more binary life status information associated with a speaker’s face. When seeing Emma Watson, one may start to think of multiple associations, among them Harry Potter, and wands, but also of “The Beauty and the Beast”, and “The Perks of Being a Wallflower”. Given the many facts an individual may know about a certain cultural figure, each specific fact may be less readily accessible and thus less influential during processing. For life status, by contrast, the associated information is likely binary (alive or not in a given year). If the uniqueness of a cue matters, then accessing information based on a face cue should be easier for binary cues than facts that are part of a larger category of information (e.g., all the films someone has starred in). Evidence of rapid effects of prior long-term knowledge from previous studies [e.g., @Hagoort2004] suggest that, in the presence of long-term knowledge about the cultural figures, violations of such prior knowledge should elicit processing costs. The present study therefore extends the previous findings of rapid effects for violations of high-level world knowledge [e.g., @Hagoort2004] to violations of prior knowledge about a given well-known figure (activated by their picture) and temporal lifetime and factual accomplishment information.
  
  We presented participants with pictures of well-known cultural figures, followed by sentences in which the cultural figure describes an accomplishment ("fact") of theirs, as well as the year it happened. We manipulated whether the fact and year were true for the cultural figure or not. We expected to find early effects of *year* and *fact* congruence at the respective regions reflecting the influence of long-term knowledge prompted by the trial-initial picture, and later/cumulative effects at these regions reflecting the influence of the later *name* region. Differences in the emergence and size of *year congruence* and *fact congruence* effects were also of interest, with implications for processing preferences for temporal (*year*) versus referential (*fact*) processes. Lastly, effects were expected to be present in the data filtered for accurate long-term knowledge, and to be absent or smaller in the unfiltered data, reflecting the effect of long-term knowledge present in the filtered data.

As expected, main effects of both **year** and **fact congruence** emerged in **first-pass reading time** and **total reading times** at their relative regions in filtered analyses. This suggests each type of information was rapidly available after presentation of a picture of a well-known speaker (first-pass reading time), and that violations of this information were not quickly resolved (total reading time). However, effects of **fact congruence** at the *name* region were present in unfiltered data (but not filtered data), with no effects of **year congruence**. This suggests asymmetries in the processing of the two types of information when prior world knowledge is more variable. The observed effect differences could be attributed to a preference for attending to referential relations (*fact* region), compared to temporal relations (*year* region) when encountering contrasting information, such as long-term information activated by the *name* region in unfiltered trials. While a given year requires some temporal relations be computed for a cultural figure's lifetime, preferential attention may have been given to *fact*-*name* relations at name presentation when the picture was not recognised, leading to the *fact congruence* effects at the *name* region (e.g., *2018*...*the song* ***I Shot the Sheriff***...*John Lennon*).

This leads to the last research question, in which we were interested in investigating the role of long-term knowledge in the processing of temporal and factual relations to a given cultural figure. @Troyer2018 reported individual-level differences in the processing of sentences about the Wizarding World of Harry Potter, finding graded N400 effects positively correlated with a participant's score on a Harry Potter familiarity questionnaire. Given these findings, we expected to find differences in effects when trials were filtered to exclude those that received incorrect world-knowledge prompt responses (i.e., trial-initial picture recognition, post-experimental speaker-year and -fact congruence responses). Indeed, we observed differences between the unfiltered and filtered data, suggesting that the presence of long-term knowledge when prompted prior to sentence presentation by a picture did play a role in processing. Where effects were present in both filtered and unfiltered trials at the *year* and *fact* regions, effects were larger in the filtered data. As the filtered data consisted of fewer observations than the unfiltered data, the emergence of stronger effects in the former indicates a more robust effect compared to the larger unfiltered dataset which had smaller effects. This could indicate that the filtered data points were driving the effect in the unfiltered data, in which they were also included. Only in the *name* region were effects present in the unfiltered data but not the filtered data, but only for *fact congruence*. This could be attribributed to the new information provided by the name when the speaker was not recognised by their picture. In the presence of more variable knowledge of a given cultural figure, it seems knowledge of their accomplishments is more reliable than knowledge of when they were born or died.

The findings from Experiments 1 and 2 suggest that high-level information about well-known individuals is immediately integrated with long-term knowledge activated by their picture. This was true for both years which did not fall within the bounds of the speaker's lifetime (e.g., *Angela Merkel* - *1930*), and for 'facts' that were not true (e.g., *Angela Merkel* - *China*). These effects were stronger at their relative critical regions (*year* and *fact*) when data were filtered to exclude trials containing false world-knowledge responses, indicating an effect of trial-specific long-term knowledge, mirroring individual-level graded effects in @Troyer2018. Conversely, effects of *fact congruence* at the *name* region were more robust for unfiltered data at the *name* region, indicating that the additional speaker information provided by the name may have been more beneficial in trials in which participants had partial long-term knowledge of the speaker, or did not recognise their picture. The absence of *year congruence* effects at the *name* region, but presence of *fact congruence* effects in the unfiltered data at the same region, suggest that referential (*fact*-*name*) processes may outweigh temporal relations (*year*-*name*) relations when long-term knowledge is more variable. These findings suggest these types of relations are rapidly available during langauge processing, but that their are differences in their processing in the presence of variable prior knowledge.

## Moving forward: EEG

Experiment 3 will be an EEG experiment in which participants are presented with the same stimuli from Experiments 1 and 2. Instead of reading each critical sentence in its entirety, linguistic stimuli will be presented in rapid serial visual presentation (RSVP). Experiment 3 will not contain the factor fact congruence, thereby reducing the design to a single 2-level factor (life-year congruence: congruent, incongruent). 

Before running the EEG pilot, the critical stimuli will be reduced to remove the counterbalamcing for fact-congruence. Because of this, we only require 80 cultural figures instead of the 160 that were included to account for life-year and fact congruence counterbalancing within items. Filler items will also be minimally altered to contain systematic world knowledge and morphosyntactic violations in order to elicit N400 and P600 effects from the participants, which can be compared to the relevant effect elicited at the critical region. See @sec-stimuli-changes for more detail abou the stimuli changes. A pilot study will be run with a training/testing session as in Experiment 2 (see @sec-eeg-pilot).


