---
title: "Teaching"
---

```{r}
#| message: false
# load packages
pacman::p_load(tidyverse, knitr, kableExtra, gt)
```

## Workshops

```{r}
# workshop courses
tribble(
  ~ "Year", ~ "Workshop title", ~ "Institution", ~ "Link", 
  "2024", "Reproducible Workflow in R", "<a href = 'https://www.leibniz-zas.de/de/'>Leibniz Institut for General Linguistics</a> (Leibniz-Zentrum Allgemeine Sprachwissenschaft (ZAS)), Berlin, Germany", "https://daniela-palleschi.github.io/zas-reproducibility-2024/",
  "2024", "Open Science Practices for Linguistic Research: Reproducible Analyses in R", "<a href = 'https://ssol.ff.cuni.cz/ssol-2024/'>Summer School of Linguistics</a> at the University of South Bohemia in České Budějovice (Budweis), Czechia", "https://daniela-palleschi.github.io/SSOL24-reproducibility-workshop/",
  "2020", "Introduction to Ibex and PennController: Internet Based Experiments", "Institut für deutsche Sprache und Linguistik (Department of German Language and Linguistics), Humboldt-Universität zu Berlin", "https://box.hu-berlin.de/d/ff964c88ad9c47e781b5/"
) |>
  mutate(Institution = map(Institution, gt::html)) |>
  mutate(
    `Workshop title` = ifelse(
      Link == "NA",
      `Workshop title`,
      glue::glue("[{`Workshop title`}]({Link})")
    ),
    `Workshop title` = map(`Workshop title`, gt::md)
  ) |>
  select(-Link) |>
  gt()  |> 
  cols_align(align = "left",
             columns = everything()) 
```

## Semester-length courses

All courses listed were taught at the Institut für deutsche Sprache und Linguistik (Department of German Language and Linguistics), Humboldt-Universität zu Berlin, in addition to any other institutes given.

```{r}
# past IdSL courses
tribble(
  ~"Year", ~"Semester", ~"Course title", ~"Level", ~"Link",
  "2024", "SoSe", "Open Science Practices: Implementing a Reproducible Analysis Workflow", "M.A.","https://daniela-palleschi.github.io/r4reproducibility/",
  "2024", "SoSe", "Angewandte Datenverarbeitung und Visualisierung: R für Linguistik und Sozialwissenschaften (EN: Applied data analysis and visualisation: R for linguists and social sciences)", "B.A.","https://daniela-palleschi.github.io/r4ling/",
  "2023/24", "WiSe", "Regression for Linguists", "M.A.","https://daniela-palleschi.github.io/reg4ling/",
  "2023", "SoSe", "Angewandte Datenanalyse und -visualisierung (EN: Applied data analysis and visualisation)", "B.A.", "https://daniela-palleschi.github.io/r4ling/",
  "2023", "SoSe", "Reproducible analyses for eye-tracking reading data", "M.A.", "https://daniela-palleschi.github.io/repo-eda/",
  "2023", "SoSe", "Angewandte Datenanalyse und -visualisierung (EN: Applied data analysis and visualisation)", "B.A.", "NA",
  "2020", "SoSe", "Language and the Brain (Tutorial)", "M.A. (Berlin School of Mind and Brain)", "NA",
  "2019", "SoSe", "Language and the Brain (Tutorial)", "M.A. (Berlin School of Mind and Brain)", "NA",
  "2018/19", "WiSe", "Introduction to Statistics for Linguistics with R and RStudio", "M.A.", "NA",
  "2018", "SoSe", "Language and the Brain (Tutorial)", "M.A. (Berlin School of Mind and Brain)", "NA"
  ) |> 
  mutate(
    `Course title` = ifelse(Link=="NA", `Course title`, glue::glue("[{`Course title`}]({Link})")),
        `Course title` = map(`Course title`, gt::md)) |> 
  select(-Link) |> 
  gt() |>  
  cols_align(
    align = "left",
    columns = everything()
  ) 

## solution for adding hyperlinks to tibbles: https://community.rstudio.com/t/create-interactive-links-in-gt-table-in-rmarkdown/70266/2
```

